modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/J-Dill/NoMoWanderer/issues"
license="MIT License"
[[mods]]
modId="nomowanderer"
version="${file.jarVersion}"
displayName="NoMoWanderer"
credits="Big shoutout to computers, without you I would have no job."
authors="JDill"
description='''
Adds a block and an item that prevents configurable entity spawns.
Default entities are the Wandering Trader and the Plague Doctor from the Rats mod.
'''
[[dependencies.nomowanderer]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="curios"
    mandatory=false
    versionRange="[1.18.1-5,)"
    ordering="NONE"
    side="BOTH"