modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
#issueTrackerURL="http://github.com/strikerrocker/VanillaTweaks/issues/" #optional
license="MIT License"
[[mods]] #mandatory
modId="nomowanderer" #mandatory
version="1.15.2_1.2" #mandatory
displayName="NoMoWanderer" #mandatory
credits="Big shoutout to computers, without you I would have no job." #optional
authors="djmanly" #optional
description='''Adds a block and an item that prevents Wandering Trader spawn.'''
[[dependencies.nomowanderer]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="jei"
    mandatory=false
    versionRange="[7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="baubles"
    mandatory=false
    versionRange="[1.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="curios"
    mandatory=false
    versionRange="[1.16.2-4,)"
    ordering="NONE"
    side="BOTH"