modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
#issueTrackerURL="http://github.com/strikerrocker/VanillaTweaks/issues/" #optional
[[mods]] #mandatory
modId="nomowanderer" #mandatory
version="1.0" #mandatory
displayName="NoMoWanderer" #mandatory
credits="Big shoutout to computers, without you I would have no job." #optional
authors="djmanly" #optional
description='''Adds a block that prevents Wandering Trader spawn.'''
[[dependencies.nomowanderer]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="jei"
    mandatory=false
    versionRange="[6,)"
    ordering="NONE"
    side="BOTH"