modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
issueTrackerURL="https://github.com/J-Dill/NoMoWanderer/issues" #optional
license="MIT License"
[[mods]] #mandatory
modId="nomowanderer" #mandatory
version="${file.jarVersion}" #mandatory
displayName="NoMoWanderer" #mandatory
credits="Big shoutout to computers, without you I would have no job." #optional
authors="djmanly" #optional
description='''
Adds a block and an item that prevents configurable entity spawns.
Default entities are the Wandering Trader and the Plague Doctor from the Rats mod.
'''
[[dependencies.nomowanderer]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="jei"
    mandatory=false
    versionRange="[7.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="baubles"
    mandatory=false
    versionRange="[1.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomowanderer]]
    modId="curios"
    mandatory=false
    versionRange="[1.16.5-4,)"
    ordering="NONE"
    side="BOTH"